//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeCloset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public Accessory()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int AccessoriesID { get; set; }
        public string Name { get; set; }
        public string ClothingType { get; set; }
        public Nullable<int> OutfitsID { get; set; }
        public string Brand { get; set; }
        public string Photo { get; set; }
        public string Color { get; set; }
        public string Occasion { get; set; }
        public string Season { get; set; }
        public Nullable<bool> Favorite { get; set; }
        public Nullable<int> TimesWorn { get; set; }
        public Nullable<bool> Dirty { get; set; }
    
        public virtual Outfit Outfit { get; set; }
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
